jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
      - etapa : prueba
      guión : ./test 1
    - No se requiere el nombre de la etapa # , continuará usando `test`
